[tool.poetry]
name = "music-sync"
version = "0.1.0"
description = "Sync liked tracks from streaming services to Bandcamp/Apple Music"
authors = ["Alex Yule <adyule@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.5"
python-dotenv = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
